### PR TITLE
RPM generation

### PR DESCRIPTION
**Pull request by arodriguezdlc**

### CODE REVIEW

**Comment by arodriguezdlc** [comment]
Please, first merge to master #38 pull request.

**Review by Bigomby — CHANGES_REQUESTED** [review]
Can you make some tests for the RPM generation?

**Review by Bigomby — COMMENTED** [review]
Its absolutely necessary for the `f2k.service` file to be on the root dir?

**Comment by Bigomby** [comment]
Sice #38 is merged you may want to update your pr.

**Pull request closed without merging**
